twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: ' '

when@test:
    twig:
        strict_variables: true
