version: '3.8'
services:
    db:
        image: mysql:8
        ports: [ '3306:3306' ]
        restart: unless-stopped
        volumes:
            - './data/db:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD

    adminer:
        image: adminer:4.7
        restart: unless-stopped
        ports: [ '8080:8080' ]

    php:
        depends_on:
            - rabbitmq
            - db
        restart: unless-stopped
        build: ./docker/php
        volumes:
            - './:/var/www:cached'
            - /var/www/data/ # exclude data
            - './vendor:/var/www/vendor:cached'
            - './var:/var/www/var'
#        environment:
#            XDEBUG_CONFIG: client_host=192.168.117.1

    nginx:
        depends_on:
            - php
        restart: unless-stopped
        build: ./docker/nginx
        ports: [ '80:80' ]
        volumes:
            - './public:/var/www/public'

    rabbitmq:
        image: rabbitmq:3.8-management
        ports: [ '15672:15672' ]
        environment:
            - RABBITMQ_DEFAULT_USER
            - RABBITMQ_DEFAULT_PASS

    mailer:
        image: schickling/mailcatcher
        restart: unless-stopped
        ports: [ '1025:1080' ]

    redis:
        image: library/redis:6.2-alpine
        restart: unless-stopped
        volumes:
            - './data/redis:/data'
