controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale?}

homepage:
    path: "/"
    controller: App\Controller\HomeController::home
